Merge branch 'upstream-release-1.27.1'
gardener/autoscaler pull request #225
Opened 2023-05-23 09:50 UTC by ashwani2k

**What this PR does / why we need it**:
Sync autoscaler with upstream v1.27.1 

**Which issue(s) this PR fixes**:
Fixes #191 

**Special notes for your reviewer**:
With release of v1.27 they have released v1.27.1 and v1.27.0 as mirror releases. So for future ease I have synced with v1.27.1
Please read the SYNC_CHANGES-1.27 for what has changed with this release. 

**Release note**:

```other operator
Synced the changes till v1.27.1 of upstream autoscaler. 
```

2023-06-26 10:56 UTC, rishabh-11 commented on cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.27.md
> +  - A new controller `balancer` is added to the `autoscaler` repo at a peer level to `cluster-autoscaler` and `vertical-pod-autoscaler`. Currently with this release we have not consumed this in our u
```suggestion
A new controller `balancer` is added to the `autoscaler` repo at a peer level to `cluster-autoscaler` and `vertical-pod-autoscaler`. We will need further investigation to see if this component is useful for gardener. 
```

2023-06-27 07:10 UTC, rishabh-11 requested changes
Thanks for the changes. Some minor changes needed, rest looks good

2023-06-27 07:10 UTC, rishabh-11 commented on cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.27.md
> +  - A new controller `balancer` is added to the `autoscaler` repo at a peer level to `cluster-autoscaler` and `vertical-pod-autoscaler`. Currently with this release we have not consumed this in our u
```suggestion
  - A new controller `balancer` is added to the `autoscaler` repo at a peer level to `cluster-autoscaler` and `vertical-pod-autoscaler`. We will need further investigation to see if this component is useful for gardener. 
```

2023-06-27 07:10 UTC, rishabh-11 commented on cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.27.md
> + - `Go-Lang` version updated from v1.19.5 to v1.20.4 in -
```suggestion
 - `Go-Lang` version updated from v1.19.5 to v1.20.5 in - 
```

2023-06-27 07:10 UTC, rishabh-11 commented on cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.27.md
> + - The cloudProvider interface has added a new method [`GetNodeGupConfig`](https://github.com/kubernetes/autoscaler/blob/41a957b7e8b8630cb4c3e7811bdcecf85c510f09/cluster-autoscaler/cloudprovider/clou
```
`GetNodeGupConfig` -> `GetNodeGpuConfig`
```

2023-06-27 07:10 UTC, rishabh-11 commented on cluster-autoscaler/clusterstate/clusterstate.go
>  type Readiness struct {
The `Readiness` struct field values are changed to an array of strings from int. Can you add this in the sync changes file? It's not there in the upstream rel notes.

2023-06-27 09:57 UTC, rishabh-11 commented on cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.27.md
> + - The cloudProvider interface has added a new method [`GetNodeGupConfig`](https://github.com/kubernetes/autoscaler/blob/41a957b7e8b8630cb4c3e7811bdcecf85c510f09/cluster-autoscaler/cloudprovider/clou
[285628a](https://github.com/gardener/autoscaler/pull/225/commits/285628ae4325b795dd264dee313a7a296fdfc188) has `GetNodGpuConfig` and not `GetNodeGpuConfig`

2023-06-27 10:12 UTC, ashwani2k commented on cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.27.md
> + - The cloudProvider interface has added a new method [`GetNodeGupConfig`](https://github.com/kubernetes/autoscaler/blob/41a957b7e8b8630cb4c3e7811bdcecf85c510f09/cluster-autoscaler/cloudprovider/clou
Fixed with https://github.com/gardener/autoscaler/commit/8ef9faadcbf7b3ca11a2cc1bc17d9e6a7be74ddb

2023-06-27 12:03 UTC, rishabh-11 approved these changes
/lgtm

2023-06-27 12:55 UTC, merged