Sync with upstream `v1.29.4`
gardener/autoscaler pull request #327
Opened 2024-09-27 08:52 UTC by rishabh-11

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #326 

**Special notes for your reviewer**:

**Release note**:

```other operator
Synced with upstream v1.29.4
```

2024-09-27 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/autoscaler?pullRequest=327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gardener/autoscaler?pullRequest=327) before we can accept your contribution.<br/>**1** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: rishabh-11<br/>:x: kdw174<br/>:x: k8s-ci-robot<br/>:x: MaciekPytel<br/>:x: Shubham82<br/>:x: gjtempleton<br/>:x: wenxuan0923<br/>:x: Silvest89<br/>:x: apricote<br/>:x: BigDarkClown<br/>:x: kmsarabu<br/>:x: damikag<br/>:x: maksim-paskal<br/>:x: vadasambar<br/>:x: x13n<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/autoscaler?pullRequest=327) it.</sub>

2024-10-02 19:03 UTC, aaronfern requested changes
Looks good in general

In addition to the two changes asked, I have one question, and one more change
1. Do we not update `SYNC-CHANGES` with patch versions?
2. Can you please update the docstring of [`machine_cloud_provider.GetOptions`](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go#L477-L479) to the new docstring [here](https://github.com/gardener/autoscaler/pull/327/files#diff-df1da4cc9174c37604da59b5db78a797e3b6450c71490f26a5b4a3f74263be12R235-R237)

2024-10-02 19:03 UTC, aaronfern commented on cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
> +		klog.V(2).Infof("[DeleteMachines] No machines to delete")
`Info` should be sufficient, no?
```suggestion
		klog.V(2).Info("[DeleteMachines] No machines to delete")
```

2024-10-02 19:03 UTC, aaronfern commented on cluster-autoscaler/main.go
> -
This is removed by error ig. Can you please re add this?

2024-10-07 12:04 UTC, rishabh-11 commented on cluster-autoscaler/main.go
> -
Did not remove it by mistake. There is no `Version` file anymore. So we can either add a version file and then reintroduce this or we can get rid of this.

2024-10-09 08:10 UTC, rishabh-11 commented
> Do we not update SYNC-CHANGES with patch versions?

It is not needed IMO as the sync changes are for minor and not patch versions.

> Can you please update the docstring of [machine_cloud_provider.GetOptions](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go#L477-L479) to the new docstring [here](https://github.com/gardener/autoscaler/pull/327/files#diff-df1da4cc9174c37604da59b5db78a797e3b6450c71490f26a5b4a3f74263be12R235-R237)

The docstring is part of 1.30 and is also not present upstream. I think it is fine for us to keep it like this.

2024-10-21 05:36 UTC, rishabh-11 commented on cluster-autoscaler/main.go
> -
I checked and it is working fine. It uses the VERSION file at the root of the repo, not the version dir. I have added this piece of code back

2024-10-22 08:54 UTC, aaronfern commented
> I think it is fine for us to keep it like this

Okay, fair enough for me then

2024-10-22 08:55 UTC, aaronfern approved these changes
Thanks for the changes
/lgtm

2024-10-23 06:44 UTC, merged